#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

exec 3>&1
exec 1>&2

payload="$(cat <&0)"

debug=$(jq -r '.source.debug // "false"' <<< "$payload")

if [ "$0" = '/opt/resource/out' ]; then
    jq -n '{}' >&3  # noop
    exit
fi

oauth_consumer_key=$(jq -r '.source.oauth_consumer_key // ""' <<< "$payload")

if [ -n "$oauth_consumer_key" ]; then
    oauth_token=$(jq -r '.source.oauth_token // ""' <<< "$payload")
    oauth_token_secret=$(jq -r '.source.oauth_token_secret // ""' <<< "$payload")
    export LAUNCHPAD_TOKEN="$oauth_token:$oauth_token_secret:$oauth_consumer_key"
else
    export LAUNCHPAD_TOKEN="::"
fi

if [ "$debug" = "verbose" ]; then
    set -x
fi

if [ "$(jq -r '.source | has("repo")' <<< "$payload")" = 'true' ]; then
    case "$(jq -r '.source.repo | type' <<< "$payload")" in
        ('string')
            repo=$(jq -r .source.repo <<< "$payload")
            ;;
        (*)
            echo "Invalid input for .source.repo"
            exit 1
            ;;
    esac
else
    echo "You need to provide the repo such as ~oem-solutions-engineers/pc-enablement/+git/oem-scripts against https://code.launchpad.net/~oem-solutions-engineers/pc-enablement/+git/oem-scripts."
    exit 1
fi

if [ "$(jq -r '.source | has("queue_status")' <<< "$payload")" = 'true' ]; then
    case "$(jq -r '.source.queue_status | type' <<< "$payload")" in
        ('string')
            queue_status=("$(jq -r .source.queue_status <<< "$payload")")
            ;;
        ('array')
            mapfile -t queue_status < <(jq -r '.source.queue_status | .[]' <<< "$payload")
            ;;
        (*)
            echo "Invalid input for .source.queue_status"
            exit 1
            ;;
    esac
else
    queue_status=()
fi

case "$0" in
    ('/opt/resource/in'|'/opt/resource/out')
        cd "$1"
        ;;
esac

files=()
case "$0" in
    ('/opt/resource/check'|'/opt/resource/in')
        payload=$(launchpad-api get "$repo" ws.op==getMergeProposals)
        while read -r self_link; do
            file=$(basename "${self_link}").json
            files+=("$file")
            jq -r ".entries | .[] | select(.self_link==\"${self_link}\")" <<<"$payload" > "$file"
        done < <(jq -r '.entries | .[] | .self_link' <<<"$payload")
        if [ -n "${files[*]}" ]; then
            digest="sha256:$(cat "${files[@]}" | sha256sum | awk '{print $1}')"
        else
            digest=""
        fi
        ;;
    ('/opt/resource/out')
        ;;
esac

case "$0" in
    ('/opt/resource/check')
        if [ -n "$digest" ]; then
            json="$(cat <<ENDLINE
[
    {
        "digest": "$digest"
    }
]
ENDLINE
)"
        else
            json="[]"
        fi
        ;;
    ('/opt/resource/in')
        if [ -n "$digest" ]; then
            json="$(cat <<ENDLINE
{
    "version": {
        "digest": "$digest"
    },
    "metadata": [
        {
            "name": "url",
            "value": "https://code.launchpad.net/$repo"
        }
    ]
}
ENDLINE
)"
        else
            json="{}"
        fi
        ;;
esac

jq -n "$json" >&3
